# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
