# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-29 11:14
from __future__ import unicode_literals

import bookstudio.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=bookstudio.books.models.books_directory_path),
        ),
    ]
